### ISSUE TITLE
Graffiti tutorial is still using deprecated Ojwidgets module

### ISSUE THREAD

**Issue by balat** [ocsigen/tutorial#21]
We need to replace by Ocsigen_widgets (and test)

**Comment by balat** [comment]
@vasilisp Do you have time to do this?

**Comment by vasilisp** [comment]
@balat, before releasing Eliom? I don't know these projects very well. Do the widgets in `Ojwidgets` map very straightforwardly to `Ocsigen_widgets`? If yes, I can try, if no, I think I should stick to the more critical tasks so that there is some hope of releasing on the tentative date discussed :).

**Comment by vasilisp** [comment]
@balat, actually the code in the graffiti repo already uses `ocsigen-widgets`, not `ojwidgets`, so it is probably a copy-paste job that I can do.

**Comment by balat** [comment]
Yes it's probably just a matter of copy-pasting.

**Comment by vasilisp** [comment]
Done.
